# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 47d39bc292a5ccee58182457c48a6d1998b8d26b5f0d216b955f0c259a256d614001622cd2af3868e6c15aedb234757b329c7fce0de5b2ff848b57d2a147d201

test:
  secret_key_base: 45e495ff5082e5cc0988ae1aab62571acb10f2d401572c5080999e7f6dbfa0eb6d57b85b2cd2cef0a3e1bbfd8ae604b2a506d4275dc2ed4e1ad4338d6cfaad1a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
